name: Python Unit Tests and Cypress Tests

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '16.x'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Python dependencies
      run: pip install -r backend/requirements.txt
    - name: Run Python unit tests
      run: python -m unittest backend/tests/test_lambda_function.py

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install JavaScript dependencies
      run: npm ci
    - name: Install Cypress dependencies
      run: npm install cypress --save-dev
    - name: Run Cypress tests
      run: npx cypress run
